version: '3'
services:
  main:
    hostname: 003-icetea
    build: .
    image: 003_icetea:001
    container_name: 003_icetea
    volumes:
      - ./works:/opt/works
    networks:
      eth8:
        ipv4_address: 192.168.187.11

networks:
  eth8:
    external: true
