version: '3'
services:
  main:
    hostname: 004-latex
    build: .
    image: 004_latex:001
    container_name: 004_latex
    volumes:
      - ./works:/opt/works
    networks:
      eth200:
        ipv4_address: 192.168.200.4

networks:
  eth200:
    external: true
